import mongoose from 'mongoose';
import env from '#start/env';

import Region from '#models/Region';
import Country from '#models/Country';
import OtherCategory from '#models/OtherCategory';

interface CountryData {
	name: string;
	code: string;
}
interface DataStructure {
	[key: string]: CountryData[];
}

const DATA: DataStructure = {
	EMEA: [
		{ name: 'Afghanistan', code: 'AF' },
		{ name: 'Aland Islands', code: 'AX' },
		{ name: 'Albania', code: 'AL' },
		{ name: 'Algeria', code: 'DZ' },
		{ name: 'Andorra', code: 'AD' },
		{ name: 'Angola', code: 'AO' },
		{ name: 'Antarctica', code: 'AQ' },
		{ name: 'Armenia', code: 'AM' },
		{ name: 'Austria', code: 'AT' },
		{ name: 'Azerbaijan', code: 'AZ' },
		{ name: 'Bahrain', code: 'BH' },
		{ name: 'Belarus', code: 'BY' },
		{ name: 'Belgium', code: 'BE' },
		{ name: 'Benin', code: 'BJ' },
		{ name: 'Bosnia and Herzegovina', code: 'BA' },
		{ name: 'Botswana', code: 'BW' },
		{ name: 'Bouvet Island', code: 'BV' },
		{ name: 'Bulgaria', code: 'BG' },
		{ name: 'Burkina Faso', code: 'BF' },
		{ name: 'Burundi', code: 'BI' },
		{ name: 'Cabo Verde', code: 'CV' },
		{ name: 'Cameroon', code: 'CM' },
		{ name: 'Central African Republic', code: 'CF' },
		{ name: 'Chad', code: 'TD' },
		{ name: 'Comoros', code: 'KM' },
		{ name: 'Congo', code: 'CG' },
		{ name: 'Cook Islands', code: 'CK' },
		{ name: 'Croatia', code: 'HR' },
		{ name: 'Curaçao', code: 'CW' },
		{ name: 'Cyprus', code: 'CY' },
		{ name: 'Czechia', code: 'CZ' },
		{ name: 'Denmark', code: 'DK' },
		{ name: 'Djibouti', code: 'DJ' },
		{ name: 'Egypt', code: 'EG' },
		{ name: 'Equatorial Guinea', code: 'GQ' },
		{ name: 'Eritrea', code: 'ER' },
		{ name: 'Estonia', code: 'EE' },
		{ name: 'Ethiopia', code: 'ET' },
		{ name: 'Faroe Islands', code: 'FO' },
		{ name: 'Finland', code: 'FI' },
		{ name: 'France', code: 'FR' },
		{ name: 'French Guiana', code: 'GF' },
		{ name: 'French Polynesia', code: 'PF' },
		{ name: 'French Southern Territories', code: 'TF' },
		{ name: 'Gabon', code: 'GA' },
		{ name: 'Gambia', code: 'GM' },
		{ name: 'Georgia', code: 'GE' },
		{ name: 'Germany', code: 'DE' },
		{ name: 'Ghana', code: 'GH' },
		{ name: 'Gibraltar', code: 'GI' },
		{ name: 'Greece', code: 'GR' },
		{ name: 'Greenland', code: 'GL' },
		{ name: 'Guadeloupe', code: 'GP' },
		{ name: 'Guernsey', code: 'GG' },
		{ name: 'Guinea', code: 'GN' },
		{ name: 'Guinea-Bissau', code: 'GW' },
		{ name: 'Heard Island and McDonald Islands', code: 'HM' },
		{ name: 'Holy See', code: 'VA' },
		{ name: 'Hungary', code: 'HU' },
		{ name: 'Iceland', code: 'IS' },
		{ name: 'Iran', code: 'IR' },
		{ name: 'Iraq', code: 'IQ' },
		{ name: 'Ireland', code: 'IE' },
		{ name: 'Isle of Man', code: 'IM' },
		{ name: 'Israel', code: 'IL' },
		{ name: 'Italy', code: 'IT' },
		{ name: 'Ivory Coast', code: 'CI' },
		{ name: 'Jersey', code: 'JE' },
		{ name: 'Jordan', code: 'JO' },
		{ name: 'Kazakhstan', code: 'KZ' },
		{ name: 'Kenya', code: 'KE' },
		{ name: 'Kuwait', code: 'KW' },
		{ name: 'Kyrgyzstan', code: 'KG' },
		{ name: 'Latvia', code: 'LV' },
		{ name: 'Lebanon', code: 'LB' },
		{ name: 'Lesotho', code: 'LS' },
		{ name: 'Liberia', code: 'LR' },
		{ name: 'Libya', code: 'LY' },
		{ name: 'Liechtenstein', code: 'LI' },
		{ name: 'Lithuania', code: 'LT' },
		{ name: 'Luxembourg', code: 'LU' },
		{ name: 'Macedonia', code: 'MK' },
		{ name: 'Madagascar', code: 'MG' },
		{ name: 'Malawi', code: 'MW' },
		{ name: 'Mali', code: 'ML' },
		{ name: 'Malta', code: 'MT' },
		{ name: 'Martinique', code: 'MQ' },
		{ name: 'Mauritania', code: 'MR' },
		{ name: 'Mauritius', code: 'MU' },
		{ name: 'Mayotte', code: 'YT' },
		{ name: 'Moldova', code: 'MD' },
		{ name: 'Monaco', code: 'MC' },
		{ name: 'Montenegro', code: 'ME' },
		{ name: 'Morocco', code: 'MA' },
		{ name: 'Mozambique', code: 'MZ' },
		{ name: 'Namibia', code: 'NA' },
		{ name: 'Netherlands', code: 'NL' },
		{ name: 'New Caledonia', code: 'NC' },
		{ name: 'Niger', code: 'NE' },
		{ name: 'Nigeria', code: 'NG' },
		{ name: 'Norway', code: 'NO' },
		{ name: 'Oman', code: 'OM' },
		{ name: 'Poland', code: 'PL' },
		{ name: 'Portugal', code: 'PT' },
		{ name: 'Qatar', code: 'QA' },
		{ name: 'Réunion', code: 'RE' },
		{ name: 'Romania', code: 'RO' },
		{ name: 'Russian Federation', code: 'RU' },
		{ name: 'Rwanda', code: 'RW' },
		{ name: 'Saint Barthelemy', code: 'BL' },
		{ name: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH' },
		{ name: 'Saint Martin', code: 'MF' },
		{ name: 'Saint Pierre and Miquelon', code: 'PM' },
		{ name: 'San Marino', code: 'SM' },
		{ name: 'Sao Tome and Principe', code: 'ST' },
		{ name: 'Saudi Arabia', code: 'SA' },
		{ name: 'Senegal', code: 'SN' },
		{ name: 'Serbia', code: 'RS' },
		{ name: 'Seychelles', code: 'SC' },
		{ name: 'Sierra Leone', code: 'SL' },
		{ name: 'Sint Maarten', code: 'SX' },
		{ name: 'Slovakia', code: 'SK' },
		{ name: 'Slovenia', code: 'SI' },
		{ name: 'Somalia', code: 'SO' },
		{ name: 'South Africa', code: 'ZA' },
		{ name: 'South Sudan', code: 'SS' },
		{ name: 'Spain', code: 'ES' },
		{ name: 'State of Palestine', code: 'PS' },
		{ name: 'Sudan', code: 'SD' },
		{ name: 'Swaziland', code: 'SZ' },
		{ name: 'Sweden', code: 'SE' },
		{ name: 'Switzerland', code: 'CH' },
		{ name: 'Syrian Arab Republic', code: 'SY' },
		{ name: 'Tajikistan', code: 'TJ' },
		{ name: 'Tanzania', code: 'TZ' },
		{ name: 'The Democratic Republic of the Congo', code: 'CD' },
		{ name: 'Togo', code: 'TG' },
		{ name: 'Tunisia', code: 'TN' },
		{ name: 'Turkey', code: 'TR' },
		{ name: 'Turkmenistan', code: 'TM' },
		{ name: 'Uganda', code: 'UG' },
		{ name: 'Ukraine', code: 'UA' },
		{ name: 'United Arab Emirates', code: 'AE' },
		{ name: 'United Kingdom', code: 'GB' },
		{ name: 'Uzbekistan', code: 'UZ' },
		{ name: 'Wallis and Futuna', code: 'WF' },
		{ name: 'Western Sahara', code: 'EH' },
		{ name: 'Yemen', code: 'YE' },
		{ name: 'Zambia', code: 'ZM' },
		{ name: 'Zimbabwe', code: 'ZW' },
	],
	LATAM: [
		{ name: 'Antigua and Barbuda', code: 'AG' },
		{ name: 'Anguilla', code: 'AI' },
		{ name: 'Argentina', code: 'AR' },
		{ name: 'Aruba', code: 'AW' },
		{ name: 'Barbados', code: 'BB' },
		{ name: 'Bermuda', code: 'BM' },
		{ name: 'Bolivia', code: 'BO' },
		{ name: 'Brazil', code: 'BR' },
		{ name: 'Bahamas', code: 'BS' },
		{ name: 'Belize', code: 'BZ' },
		{ name: 'Chile', code: 'CL' },
		{ name: 'Colombia', code: 'CO' },
		{ name: 'Costa Rica', code: 'CR' },
		{ name: 'Cuba', code: 'CU' },
		{ name: 'Dominica', code: 'DM' },
		{ name: 'Dominican Republic', code: 'DO' },
		{ name: 'Ecuador', code: 'EC' },
		{ name: 'Falkland Islands', code: 'FK' },
		{ name: 'Grenada', code: 'GD' },
		{ name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
		{ name: 'Guatemala', code: 'GT' },
		{ name: 'Guyana', code: 'GY' },
		{ name: 'Honduras', code: 'HN' },
		{ name: 'Haiti', code: 'HT' },
		{ name: 'Jamaica', code: 'JM' },
		{ name: 'Saint Kitts and Nevis', code: 'KN' },
		{ name: 'Cayman Islands', code: 'KY' },
		{ name: 'Saint Lucia', code: 'LC' },
		{ name: 'Montserrat', code: 'MS' },
		{ name: 'Mexico', code: 'MX' },
		{ name: 'Nicaragua', code: 'NI' },
		{ name: 'Panama', code: 'PA' },
		{ name: 'Peru', code: 'PE' },
		{ name: 'Puerto Rico', code: 'PR' },
		{ name: 'Paraguay', code: 'PY' },
		{ name: 'Suriname', code: 'SR' },
		{ name: 'El Salvador', code: 'SV' },
		{ name: 'Turks and Caicos Islands', code: 'TC' },
		{ name: 'Trinidad and Tobago', code: 'TT' },
		{ name: 'Uruguay', code: 'UY' },
		{ name: 'Saint Vincent and the Grenadines', code: 'VC' },
		{ name: 'Venezuela', code: 'VE' },
		{ name: 'British Virgin Islands', code: 'VG' },
		{ name: 'United States Virgin Islands', code: 'VI' },
	],
	APAC: [
		{ name: 'American Samoa', code: 'AS' },
		{ name: 'Australia', code: 'AU' },
		{ name: 'Bangladesh', code: 'BD' },
		{ name: 'Brunei', code: 'BN' },
		{ name: 'Bhutan', code: 'BT' },
		{ name: 'Cocos Islands', code: 'CC' },
		{ name: 'China', code: 'CN' },
		{ name: 'Christmas Island', code: 'CX' },
		{ name: 'Fiji', code: 'FJ' },
		{ name: 'Micronesia', code: 'FM' },
		{ name: 'Guam', code: 'GU' },
		{ name: 'Hong Kong', code: 'HK' },
		{ name: 'Indonesia', code: 'ID' },
		{ name: 'India', code: 'IN' },
		{ name: 'British Indian Ocean Territory', code: 'IO' },
		{ name: 'Japan', code: 'JP' },
		{ name: 'Cambodia', code: 'KH' },
		{ name: 'Kiribati', code: 'KI' },
		{ name: 'North Korea', code: 'KP' },
		{ name: 'South Korea', code: 'KR' },
		{ name: 'Laos', code: 'LA' },
		{ name: 'Sri Lanka', code: 'LK' },
		{ name: 'Marshall Islands', code: 'MH' },
		{ name: 'Myanmar', code: 'MM' },
		{ name: 'Mongolia', code: 'MN' },
		{ name: 'Macao', code: 'MO' },
		{ name: 'Northern Mariana Islands', code: 'MP' },
		{ name: 'Maldives', code: 'MV' },
		{ name: 'Malaysia', code: 'MY' },
		{ name: 'Norfolk Island', code: 'NF' },
		{ name: 'Nepal', code: 'NP' },
		{ name: 'Nauru', code: 'NR' },
		{ name: 'Niue', code: 'NU' },
		{ name: 'New Zealand', code: 'NZ' },
		{ name: 'Papua New Guinea', code: 'PG' },
		{ name: 'Philippines', code: 'PH' },
		{ name: 'Pakistan', code: 'PK' },
		{ name: 'Pitcairn', code: 'PN' },
		{ name: 'Palau', code: 'PW' },
		{ name: 'Solomon Islands', code: 'SB' },
		{ name: 'Singapore', code: 'SG' },
		{ name: 'Thailand', code: 'TH' },
		{ name: 'Tokelau', code: 'TK' },
		{ name: 'Timor-Leste', code: 'TL' },
		{ name: 'Tonga', code: 'TO' },
		{ name: 'Tuvalu', code: 'TV' },
		{ name: 'Taiwan', code: 'TW' },
		{ name: 'United States Minor Outlying Islands', code: 'UM' },
		{ name: 'Vietnam', code: 'VN' },
		{ name: 'Vanuatu', code: 'VU' },
		{ name: 'Samoa', code: 'WS' },
	],
	NA: [
		{ name: 'Canada', code: 'CA' },
		{ name: 'United States of America', code: 'US' },
	],
};

const DATA_OTHERS = [
	'OECD',
	'OECD BEPS',
	'Endorsed',
	'Brazil Tax Reform',
	'Plastic Tax',
	'How To',
	'International Tax',
	'Tax Career',
	'Direct Tax',
	'Indirect Tax',
	'Transfer Pricing',
	'Tax Technology',
	'UAE CIT',
	'E-Invoicing and E-Reporting',
	'Environmental Tax',
	'Personal Income Tax',
	'European Union',
	'Oceania',
];
async function categorySeeder(): Promise<void> {
	try {
		await mongoose.connect(env.get('MONGO_CONNECTION_STRING'));
		console.log('Seeder: Connected to MongoDB.');

		await Region.deleteMany({});
		await Country.deleteMany({});

		for (const regionName in DATA) {
			const regionId = regionName.toLowerCase();

			const newRegion = new Region({ _id: regionId, name: regionName });
			await newRegion.save();

			const countries = DATA[regionName];
			for (const country of countries) {
				const countryId = country.code.toLowerCase();
				const newCountry = new Country({
					_id: countryId,
					name: country.name,
					code: country.code,
					region: newRegion._id,
				});
				await newCountry.save();
			}
		}

		let otherCategoryIndex = 1;
		for (const category of DATA_OTHERS) {
			const newOtherCategory = new OtherCategory({ _id: otherCategoryIndex, name: category });
			await newOtherCategory.save();
			otherCategoryIndex++;
		}
	} catch (error) {
		console.error('Seeder: Failed to connect to MongoDB:', error);
	} finally {
		await mongoose.connection.close();
		console.log('Seeder: MongoDB connection closed.');
	}
}

categorySeeder()
	.then(() => console.log('Seeding completed!'))
	.catch((err) => console.error('Seeding failed:', err));
